/**
 * Write docs/CAPABILITIES-INDEX.md: every slash command in .claude/commands and
 * every script in scripts/, one line each, from their own first heading or
 * comment. Cortex reads this file as part of the written record
 * (lib/war-room/sources.server.ts allowlist), so "is there already a command
 * for X" is answered from the repository and not from whether someone
 * happened to mention it in Slack. On 6 Oct 2026 Cortex told TJ nobody had
 * built provider-directory curation while /data-sweep, /dedupe and
 * classify-provider-images sat in the repo unmentioned.
 *
 *   npx tsx scripts/build-capabilities-index.ts          # rewrite the file
 *   npx tsx scripts/build-capabilities-index.ts --check  # exit 1 if stale
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = join(__dirname, "..");
const OUT = join(root, "docs", "CAPABILITIES-INDEX.md");

function firstMeaningfulLine(text: string): string {
  for (const raw of text.split("\n").slice(0, 40)) {
    const line = raw
      .replace(/^#!.*$/, "")
      .replace(/^\s*(\/\*\*?|\*\/|\*|\/\/|#+)\s?/, "")
      .replace(/^>\s*/, "")
      .trim();
    if (!line) continue;
    if (/^(["']use (client|server)["'];?|import |export |const |let |var |require\(|\(async)/.test(line)) break;
    if (/^(Usage|Run|Arguments|---)/i.test(line)) continue;
    return line.replace(/\s+/g, " ").slice(0, 160);
  }
  return "";
}

function commandLines(): string[] {
  const dir = join(root, ".claude", "commands");
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => {
      const text = readFileSync(join(dir, f), "utf8");
      const title = (text.match(/^#\s+(.+)$/m)?.[1] ?? "").trim();
      const body = firstMeaningfulLine(text.replace(/^#\s+.+$/m, ""));
      return `- \`/${f.replace(/\.md$/, "")}\` — ${title}${body ? `: ${body}` : ""}`;
    });
}

function scriptLines(): string[] {
  const dir = join(root, "scripts");
  return readdirSync(dir)
    .filter((f) => /\.(ts|js|mjs|cjs|py|sh)$/.test(f) && !f.startsWith("_"))
    .sort()
    .map((f) => {
      const text = readFileSync(join(dir, f), "utf8");
      const line = firstMeaningfulLine(text);
      return `- \`scripts/${f}\`${line ? ` — ${line}` : ""}`;
    });
}

function render(): string {
  return [
    "# Capabilities index",
    "",
    "Generated by `scripts/build-capabilities-index.ts`; do not edit by hand. One line per slash command and script, from each file's own first heading or comment. Regenerate after adding or renaming one. Cortex reads this as part of the written record, so it can answer \"do we already have something for X\" from the repository.",
    "",
    "## Slash commands (`.claude/commands/`)",
    "",
    ...commandLines(),
    "",
    "## Scripts (`scripts/`)",
    "",
    ...scriptLines(),
    "",
  ].join("\n");
}

const next = render();
if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== next) {
    console.error("docs/CAPABILITIES-INDEX.md is stale. Run: npx tsx scripts/build-capabilities-index.ts");
    process.exit(1);
  }
  console.log("capabilities index is current");
} else {
  writeFileSync(OUT, next);
  console.log(`wrote ${OUT}`);
}
